import { Exercise } from "./data-manager";

export const preloadedExercises: Exercise[] = [
  { id: "exercise-1", name: "Barbell Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-2", name: "Dumbbell Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-3", name: "Incline Barbell Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-4", name: "Incline Dumbbell Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-5", name: "Decline Barbell Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-6", name: "Decline Dumbbell Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-7", name: "Push-ups", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-8", name: "Dips", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-9", name: "Machine Chest Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-10", name: "Dumbbell Flyes", muscles: ["Chest"] },
  { id: "exercise-11", name: "Cable Flyes", muscles: ["Chest"] },
  { id: "exercise-12", name: "Pec Deck Machine", muscles: ["Chest"] },
  { id: "exercise-13", name: "Barbell Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-14", name: "Front Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-15", name: "Goblet Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-16", name: "Leg Press", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-17", name: "Hack Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-18", name: "Leg Extension", muscles: ["Quads"] },
  { id: "exercise-19", name: "Leg Curl (Seated)", muscles: ["Hamstrings"] },
  { id: "exercise-20", name: "Leg Curl (Lying)", muscles: ["Hamstrings"] },
  { id: "exercise-21", name: "Romanian Deadlift (Barbell)", muscles: ["Hamstrings", "Glutes"] },
  { id: "exercise-22", name: "Romanian Deadlift (Dumbbell)", muscles: ["Hamstrings", "Glutes"] },
  { id: "exercise-23", name: "Glute Bridge", muscles: ["Glutes"] },
  { id: "exercise-24", name: "Hip Thrust (Barbell)", muscles: ["Glutes"] },
  { id: "exercise-25", name: "Calf Raise (Standing)", muscles: ["Calves"] },
  { id: "exercise-26", name: "Calf Raise (Seated)", muscles: ["Calves"] },
  { id: "exercise-27", name: "Barbell Deadlift", muscles: ["Hamstrings", "Glutes", "Back"] },
  { id: "exercise-28", name: "Sumo Deadlift", muscles: ["Hamstrings", "Glutes", "Back", "Quads"] },
  { id: "exercise-29", name: "Conventional Deadlift", muscles: ["Hamstrings", "Glutes", "Back"] },
  { id: "exercise-30", name: "Stiff-Leg Deadlift", muscles: ["Hamstrings", "Glutes"] },
  { id: "exercise-31", name: "Good Mornings", muscles: ["Hamstrings", "Lower Back"] },
  { id: "exercise-32", name: "Barbell Row", muscles: ["Back", "Biceps"] },
  { id: "exercise-33", name: "Dumbbell Row", muscles: ["Back", "Biceps"] },
  { id: "exercise-34", name: "T-Bar Row", muscles: ["Back", "Biceps"] },
  { id: "exercise-35", name: "Seated Cable Row", muscles: ["Back", "Biceps"] },
  { id: "exercise-36", name: "Lat Pulldown", muscles: ["Back", "Biceps"] },
  { id: "exercise-37", name: "Pull-ups", muscles: ["Back", "Biceps"] },
  { id: "exercise-38", name: "Chin-ups", muscles: ["Back", "Biceps"] },
  { id: "exercise-39", name: "Face Pulls", muscles: ["Upper Back", "Rear Deltoids"] },
  { id: "exercise-40", name: "Shrugs (Barbell)", muscles: ["Traps"] },
  { id: "exercise-41", name: "Shrugs (Dumbbell)", muscles: ["Traps"] },
  { id: "exercise-42", name: "Overhead Press (Barbell)", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-43", name: "Overhead Press (Dumbbell)", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-44", name: "Seated Overhead Press (Barbell)", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-45", name: "Seated Overhead Press (Dumbbell)", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-46", name: "Lateral Raises", muscles: ["Shoulders"] },
  { id: "exercise-47", name: "Front Raises", muscles: ["Shoulders"] },
  { id: "exercise-48", name: "Rear Delt Flyes", muscles: ["Shoulders", "Upper Back"] },
  { id: "exercise-49", name: "Machine Shoulder Press", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-50", name: "Upright Row", muscles: ["Shoulders", "Traps"] },
  { id: "exercise-51", name: "Barbell Bicep Curl", muscles: ["Biceps"] },
  { id: "exercise-52", name: "Dumbbell Bicep Curl", muscles: ["Biceps"] },
  { id: "exercise-53", name: "Hammer Curl", muscles: ["Biceps", "Forearms"] },
  { id: "exercise-54", name: "Concentration Curl", muscles: ["Biceps"] },
  { id: "exercise-55", name: "Preacher Curl", muscles: ["Biceps"] },
  { id: "exercise-56", name: "Cable Bicep Curl", muscles: ["Biceps"] },
  { id: "exercise-57", name: "Barbell Triceps Extension (Lying)", muscles: ["Triceps"] },
  { id: "exercise-58", name: "Dumbbell Triceps Extension (Overhead)", muscles: ["Triceps"] },
  { id: "exercise-59", name: "Cable Triceps Pushdown", muscles: ["Triceps"] },
  { id: "exercise-60", name: "Close-Grip Bench Press", muscles: ["Triceps", "Chest"] },
  { id: "exercise-61", name: "Skullcrushers", muscles: ["Triceps"] },
  { id: "exercise-62", name: "Triceps Dips (Bench)", muscles: ["Triceps", "Chest"] },
  { id: "exercise-63", name: "Triceps Kickback", muscles: ["Triceps"] },
  { id: "exercise-64", name: "Wrist Curl", muscles: ["Forearms"] },
  { id: "exercise-65", name: "Reverse Wrist Curl", muscles: ["Forearms"] },
  { id: "exercise-66", name: "Hanging Leg Raise", muscles: ["Abs"] },
  { id: "exercise-67", name: "Crunches", muscles: ["Abs"] },
  { id: "exercise-68", name: "Russian Twists", muscles: ["Abs", "Obliques"] },
  { id: "exercise-69", name: "Plank", muscles: ["Abs", "Core"] },
  { id: "exercise-70", name: "Side Plank", muscles: ["Obliques", "Core"] },
  { id: "exercise-71", name: "Bicycle Crunches", muscles: ["Abs", "Obliques"] },
  { id: "exercise-72", name: "Machine Crunches", muscles: ["Abs"] },
  { id: "exercise-73", name: "Cable Wood Chop", muscles: ["Abs", "Obliques"] },
  { id: "exercise-74", name: "Landmine Twist", muscles: ["Abs", "Obliques"] },
  { id: "exercise-75", name: "Ab Rollout", muscles: ["Abs", "Core"] },
  { id: "exercise-76", name: "Back Extension", muscles: ["Lower Back"] },
  { id: "exercise-77", name: "Hyperextension", muscles: ["Lower Back", "Glutes", "Hamstrings"] },
  { id: "exercise-78", name: "Bird Dog", muscles: ["Core", "Lower Back"] },
  { id: "exercise-79", name: "Kettlebell Swing", muscles: ["Hamstrings", "Glutes", "Lower Back", "Shoulders"] },
  { id: "exercise-80", name: "Clean and Jerk", muscles: ["Full Body"] },
  { id: "exercise-81", name: "Snatch", muscles: ["Full Body"] },
  { id: "exercise-82", name: "Push Press", muscles: ["Shoulders", "Triceps", "Legs"] },
  { id: "exercise-83", name: "Jerk", muscles: ["Shoulders", "Triceps", "Legs"] },
  { id: "exercise-84", name: "Power Clean", muscles: ["Hamstrings", "Glutes", "Back", "Shoulders"] },
  { id: "exercise-85", name: "Power Snatch", muscles: ["Hamstrings", "Glutes", "Back", "Shoulders"] },
  { id: "exercise-86", name: "Thrusters", muscles: ["Quads", "Glutes", "Shoulders", "Triceps"] },
  { id: "exercise-87", name: "Wall Balls", muscles: ["Quads", "Glutes", "Shoulders", "Chest"] },
  { id: "exercise-88", name: "Box Jumps", muscles: ["Quads", "Glutes", "Calves"] },
  { id: "exercise-89", name: "Burpees", muscles: ["Full Body"] },
  { id: "exercise-90", name: "Mountain Climbers", muscles: ["Abs", "Core", "Shoulders"] },
  { id: "exercise-91", name: "Battle Ropes", muscles: ["Shoulders", "Back", "Core"] },
  { id: "exercise-92", name: "Sled Push", muscles: ["Quads", "Glutes", "Calves"] },
  { id: "exercise-93", name: "Sled Pull", muscles: ["Hamstrings", "Glutes", "Back"] },
  { id: "exercise-94", name: "Farmers Walk", muscles: ["Forearms", "Traps", "Core"] },
  { id: "exercise-95", name: "Carries (Various)", muscles: ["Forearms", "Traps", "Core"] },
  { id: "exercise-96", name: "Tire Flips", muscles: ["Full Body"] },
  { id: "exercise-97", name: "Sledgehammer Slams", muscles: ["Core", "Shoulders", "Back"] },
  { id: "exercise-98", name: "Rope Climbs", muscles: ["Back", "Biceps", "Forearms"] },
  { id: "exercise-99", name: "Sandbag Squat", muscles: ["Quads", "Glutes", "Hamstrings", "Core"] },
  { id: "exercise-100", name: "Sandbag Lunges", muscles: ["Quads", "Glutes", "Hamstrings", "Core"] },
  { id: "exercise-101", name: "Sandbag Shouldering", muscles: ["Full Body"] },
  { id: "exercise-102", name: "Sandbag Cleans", muscles: ["Hamstrings", "Glutes", "Back", "Shoulders", "Core"] },
  { id: "exercise-103", name: "Sandbag Rows", muscles: ["Back", "Biceps", "Core"] },
  { id: "exercise-104", name: "Sandbag Overhead Press", muscles: ["Shoulders", "Triceps", "Core"] },
  { id: "exercise-105", name: "Sandbag Thrusters", muscles: ["Quads", "Glutes", "Shoulders", "Triceps", "Core"] },
  { id: "exercise-106", name: "Sandbag Carries", muscles: ["Forearms", "Traps", "Core"] },
  { id: "exercise-107", name: "Medicine Ball Slams", muscles: ["Core", "Shoulders", "Back"] },
  { id: "exercise-108", name: "Medicine Ball Russian Twists", muscles: ["Abs", "Obliques"] },
  { id: "exercise-109", name: "Medicine Ball Squat Throws", muscles: ["Quads", "Glutes", "Shoulders", "Chest"] },
  { id: "exercise-110", name: "Medicine Ball Chest Pass", muscles: ["Chest", "Shoulders", "Triceps"] },
  { id: "exercise-111", name: "Medicine Ball Overhead Throw", muscles: ["Shoulders", "Triceps", "Core"] },
  { id: "exercise-112", name: "Medicine Ball Rotational Throw", muscles: ["Obliques", "Core", "Shoulders"] },
  { id: "exercise-113", name: "TRX Row", muscles: ["Back", "Biceps"] },
  { id: "exercise-114", name: "TRX Chest Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-115", name: "TRX Bicep Curl", muscles: ["Biceps"] },
  { id: "exercise-116", name: "TRX Triceps Extension", muscles: ["Triceps"] },
  { id: "exercise-117", name: "TRX Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-118", name: "TRX Lunges", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-119", name: "TRX Plank", muscles: ["Abs", "Core"] },
  { id: "exercise-120", name: "TRX Mountain Climbers", muscles: ["Abs", "Core", "Shoulders"] },
  { id: "exercise-121", name: "TRX Pike", muscles: ["Abs", "Core", "Shoulders"] },
  { id: "exercise-122", name: "TRX Atomic Push-up", muscles: ["Chest", "Triceps", "Shoulders", "Abs", "Core"] },
  { id: "exercise-123", name: "Kettlebell Goblet Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-124", name: "Kettlebell Deadlift", muscles: ["Hamstrings", "Glutes", "Back"] },
  { id: "exercise-125", name: "Kettlebell Romanian Deadlift", muscles: ["Hamstrings", "Glutes"] },
  { id: "exercise-126", name: "Kettlebell Swings", muscles: ["Hamstrings", "Glutes", "Lower Back", "Shoulders"] },
  { id: "exercise-127", name: "Kettlebell Clean", muscles: ["Hamstrings", "Glutes", "Back", "Shoulders"] },
  { id: "exercise-128", name: "Kettlebell Snatch", muscles: ["Hamstrings", "Glutes", "Back", "Shoulders"] },
  { id: "exercise-129", name: "Kettlebell Overhead Press", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-130", name: "Kettlebell Front Squat", muscles: ["Quads", "Glutes", "Hamstrings", "Shoulders"] },
  { id: "exercise-131", name: "Kettlebell Lunges", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-132", name: "Kettlebell Rows", muscles: ["Back", "Biceps"] },
  { id: "exercise-133", name: "Kettlebell Floor Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-134", name: "Kettlebell Pullover", muscles: ["Chest", "Back"] },
  { id: "exercise-135", name: "Kettlebell Halo", muscles: ["Shoulders", "Core"] },
  { id: "exercise-136", name: "Kettlebell Windmill", muscles: ["Obliques", "Shoulders", "Hamstrings"] },
  { id: "exercise-137", name: "Kettlebell Turkish Get-up", muscles: ["Full Body"] },
  { id: "exercise-138", name: "Dumbbell Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-139", name: "Dumbbell Lunges", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-140", name: "Dumbbell Step-ups", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-141", name: "Dumbbell Romanian Deadlift", muscles: ["Hamstrings", "Glutes"] },
  { id: "exercise-142", name: "Dumbbell Rows", muscles: ["Back", "Biceps"] },
  { id: "exercise-143", name: "Dumbbell Pullover", muscles: ["Chest", "Back"] },
  { id: "exercise-144", name: "Dumbbell Overhead Press", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-145", name: "Dumbbell Lateral Raises", muscles: ["Shoulders"] },
  { id: "exercise-146", name: "Dumbbell Front Raises", muscles: ["Shoulders"] },
  { id: "exercise-147", name: "Dumbbell Rear Delt Flyes", muscles: ["Shoulders", "Upper Back"] },
  { id: "exercise-148", name: "Dumbbell Shrugs", muscles: ["Traps"] },
  { id: "exercise-149", name: "Dumbbell Bicep Curl", muscles: ["Biceps"] },
  { id: "exercise-150", name: "Dumbbell Hammer Curl", muscles: ["Biceps", "Forearms"] },
  { id: "exercise-151", name: "Dumbbell Concentration Curl", muscles: ["Biceps"] },
  { id: "exercise-152", name: "Dumbbell Preacher Curl", muscles: ["Biceps"] },
  { id: "exercise-153", name: "Dumbbell Triceps Extension (Overhead)", muscles: ["Triceps"] },
  { id: "exercise-154", name: "Dumbbell Triceps Kickback", muscles: ["Triceps"] },
  { id: "exercise-155", name: "Dumbbell Floor Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-156", name: "Dumbbell Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-157", name: "Dumbbell Incline Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-158", name: "Dumbbell Decline Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-159", name: "Dumbbell Flyes", muscles: ["Chest"] },
  { id: "exercise-160", name: "Dumbbell Pullovers", muscles: ["Chest", "Back"] },
  { id: "exercise-161", name: "Barbell Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-162", name: "Barbell Front Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-163", name: "Barbell Romanian Deadlift", muscles: ["Hamstrings", "Glutes"] },
  { id: "exercise-164", name: "Barbell Good Mornings", muscles: ["Hamstrings", "Lower Back"] },
  { id: "exercise-165", name: "Barbell Rows", muscles: ["Back", "Biceps"] },
  { id: "exercise-166", name: "Barbell Shrugs", muscles: ["Traps"] },
  { id: "exercise-167", name: "Barbell Overhead Press", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-168", name: "Barbell Seated Overhead Press", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-169", name: "Barbell Upright Row", muscles: ["Shoulders", "Traps"] },
  { id: "exercise-170", name: "Barbell Bicep Curl", muscles: ["Biceps"] },
  { id: "exercise-171", name: "Barbell Triceps Extension (Lying)", muscles: ["Triceps"] },
  { id: "exercise-172", name: "Barbell Close-Grip Bench Press", muscles: ["Triceps", "Chest"] },
  { id: "exercise-173", name: "Barbell Skullcrushers", muscles: ["Triceps"] },
  { id: "exercise-174", name: "Smith Machine Squat", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-175", name: "Smith Machine Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-176", name: "Smith Machine Incline Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-177", name: "Smith Machine Decline Bench Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-178", name: "Smith Machine Overhead Press", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-179", name: "Smith Machine Rows", muscles: ["Back", "Biceps"] },
  { id: "exercise-180", name: "Smith Machine Shrugs", muscles: ["Traps"] },
  { id: "exercise-181", name: "Cable Bicep Curl", muscles: ["Biceps"] },
  { id: "exercise-182", name: "Cable Triceps Pushdown", muscles: ["Triceps"] },
  { id: "exercise-183", name: "Cable Flyes", muscles: ["Chest"] },
  { id: "exercise-184", name: "Cable Rows (Seated)", muscles: ["Back", "Biceps"] },
  { id: "exercise-185", name: "Cable Lat Pulldown", muscles: ["Back", "Biceps"] },
  { id: "exercise-186", name: "Cable Face Pulls", muscles: ["Upper Back", "Rear Deltoids"] },
  { id: "exercise-187", name: "Cable Wood Chop", muscles: ["Abs", "Obliques"] },
  { id: "exercise-188", name: "Cable Crunches", muscles: ["Abs"] },
  { id: "exercise-189", name: "Machine Chest Press", muscles: ["Chest", "Triceps", "Shoulders"] },
  { id: "exercise-190", name: "Machine Shoulder Press", muscles: ["Shoulders", "Triceps"] },
  { id: "exercise-191", name: "Machine Leg Press", muscles: ["Quads", "Glutes", "Hamstrings"] },
  { id: "exercise-192", name: "Machine Leg Extension", muscles: ["Quads"] },
  { id: "exercise-193", name: "Machine Leg Curl (Seated)", muscles: ["Hamstrings"] },
  { id: "exercise-194", name: "Machine Leg Curl (Lying)", muscles: ["Hamstrings"] },
  { id: "exercise-195", name: "Machine Pec Deck", muscles: ["Chest"] },
  { id: "exercise-196", name: "Machine Row", muscles: ["Back", "Biceps"] },
  { id: "exercise-197", name: "Machine Lat Pulldown", muscles: ["Back", "Biceps"] },
  { id: "exercise-198", name: "Machine Bicep Curl", muscles: ["Biceps"] },
  { id: "exercise-199", name: "Machine Triceps Extension", muscles: ["Triceps"] },
  { id: "exercise-200", name: "Machine Ab Crunches", muscles: ["Abs"] },
];