name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"] # Changed from main to master based on previous git output
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify Node.js version
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install # Removed --frozen-lockfile
      - name: Build with Next.js
        run: yarn build # Build handles static export when output: 'export' is set
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the output directory from the Next.js export
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4